version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  dashboard:
    build: .
    command: streamlit run src/dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    depends_on:
      - api

  db:
    image: sqlite:latest
    volumes:
      - ./data/fintech.db:/data/fintech.db

networks:
  default:
    name: fintech-inference-network
